"""add requests to api_keys

Revision ID: 753c3b3c6280
Revises: a0d03e0b3109
Create Date: 2026-03-18 16:46:14.300430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753c3b3c6280'
down_revision = 'a0d03e0b3109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requests', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_column('requests')

    # ### end Alembic commands ###
