{{- if and .Values.redis.enabled .Values.redis.auth.enabled (not .Values.redis.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lumen.fullname" . }}-redis
  labels:
    {{- include "lumen.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
{{- end }}
